name: Lingtingon
on: [push]
jobs:
  Linting:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node: [16.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkoout out the repository
        uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Bootstraping packages
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3.0.8
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        run: npm install
      - name: Get files changes
        id: changed_files
        uses: trilom/file-changes-action@v1.2.4
        with:
          output: 'json'
          fileOutput: 'csv'
      - run: |
          echo Added files: ${{ steps.changed_files.outputs.files_added }}
          echo Changed files: ${{ steps.changed_files.outputs.files_modified }}
          echo Removed files: ${{ steps.changed_files.outputs.files_removes }}
      - name: ESLint
        if: ${{ always() && (steps.changed_files.outputs.files_added || steps.changed_files.outputs.files_modified) }}
        run: npm run test:lint:js --config ./.eslintrc.js --ignore-path ./.eslintignore ${{ steps.get_file_changes.outputs.files_added }} ${{ steps.get_file_changes.outputs.files_modified }}
      - name: Stylelint
        if: ${{ always() && (steps.changed_files.outputs.files_added || steps.changed_files.outputs.files_modified) }}
        run: npm run test:lint:scss --config ./.stylelintrc.js  --ignore-path ./.stylelintignore --allow-empty-input ${{ steps.get_file_changes.outputs.files_added }} ${{ steps.get_file_changes.outputs.files_modified }}